### ISSUE TITLE
Not working, error -> 'Site not supported / does not have audio challenges'

### ISSUE THREAD

**Issue by seadhy** [useragents/Funcaptcha-Audio-Solver#11]
Although I tried it on 2 different sites, it gave the error 'Site not supported / does not have audio challenges' on both. Also, I can't reach you on discord, your invitation is broken.

I'm trying on the codes you gave, the only thing I changed is:

```py
funcap = funcaptcha(
	public_key = "69A21A01-CC7B-B9C6-0F9A-E7FA06677FFC", 
	site = "https://api.funcaptcha.com/fc/api/nojs/?pkey=69A21A01-CC7B-B9C6-0F9A-E7FA06677FFC"
)
```

**Comment by useragents** [comment]
@seadhy The invite is fixed. The site value will not work. Put the site you are solving audio on.
